const ERROR_CODES = {
    NO_USERNAME: 1,
    NO_PASSWORD: 2,
    NO_EMAIL: 3,
    USER_NOT_FOUND: 4,
    INCORRECT_PASSWORD: 5,
    EMAIL_ALREADY_TAKEN: 6,
    USERNAME_ALREADY_TAKEN: 7,
    EMAIL_REGEX_NO_MATCH: 8,
    NO_FILE_ATTACHED: 9
}

module.exports = ERROR_CODES;